name: Deployment pipeline

env:
  CONDITION: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ', '), '#skip') }}

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  deployment_pipeline:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run lint
      - name: Build app
        run: npm run build
      #- name: Test Pages
      #  run: npm run test
      #- name: Install Playwright Browsers
      #  run: npx playwright install --with-deps
      #- name: Run Playwright tests
      #  run: npm run test:e2e
      #- uses: actions/upload-artifact@v4
      #  if: ${{ !cancelled() }}
      #  with:
      #    name: playwright-report
      #    path: playwright-report/
      #    retention-days: 30
  #     - name: Trigger Deployment
  #       if: ${{ env.CONDITION == 'true' }}
  #       run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
  #     - name: Notify Failure
  #       if: ${{ failure() }}
  #       uses: Ilshidur/action-discord@master
  #       env:
  #         DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
  #         DISCORD_EMBEDS: |
  #           [
  #             {
  #               "description": "commit ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }} by shubhvarshney broke the build :(",
  #               "footer": { "text": "Severity: Error" },
  #               "color": 16711680
  #             }
  #           ]
  #       with:
  #         args: 'Build failed'

  # tag_release:
  #   name: tag
  #   needs: [simple_deployment_pipeline]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Bump version and push tag
  #       if: ${{ env.CONDITION == 'true' }}
  #       uses: anothrNick/github-tag-action@v1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         DEFAULT_BUMP: patch
  #     - name: Notify Success
  #       if: ${{ env.CONDITION == 'true' && success() }}
  #       uses: Ilshidur/action-discord@master
  #       env:
  #         DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
  #         DISCORD_EMBEDS: |
  #           [
  #             {
  #               "description": "to https://pokedex-b0tk.onrender.com/ by shubhvarshney",
  #               "footer": { "text": "Severity: Informational" },
  #               "color": 65280
  #             }
  #           ]
  #       with:
  #         args: 'A new version of Pokedex deployed'